import { createSlice } from "@reduxjs/toolkit"

const uiSlice = createSlice({
    name: "ui",
    initialState: { cartIsVisible: false },
    reducers: {
        toggle(state) {
            state.cartIsVisible = !state.cartIsVisible;
        }
    }
})

export const uiActions = uiSlice.actions; //.actions is automatically generated by createSlice().

export default uiSlice;